#!/bin/bash

REBASE_ACTION=edit

while getopts m ch; do
	case $ch in
		(m) REBASE_ACTION=reword;;
	esac
done
shift $(( $OPTIND - 1 ))

cid=$(git rev-parse --short "$1")

SED="sed -i '/^pick $cid/ s/pick/$REBASE_ACTION/'"
git -c sequence.editor="$SED" rebase -i ${cid}^
