#!/bin/bash

usage() {
	echo "${0##*/}: usage: ${0##*/} [-c]"
}

use_commit=0

while getopts c ch; do
	case $ch in
	c)	use_commit=1
		;;

	*)	usage >&2
		exit 2
		;;
	esac
done

cd "$(git rev-parse --show-toplevel)" || exit 1

files_to_edit=()

if [[ $use_commit -eq 1 ]]; then
	mapfile -d '' -t files_to_edit < <(git diff --name-only -z "HEAD^")
else
	mapfile -d '' -t files_to_edit < <(git diff --name-only -z HEAD)
fi

if ! (( ${#files_to_edit[@]} )); then
	echo "No work to resume."
	exit
fi

${VISUAL:-vim} -p "${files_to_edit[@]}"
